import React from 'react'
import { Provider } from 'react-redux'
import { Select } from '../Select'
import { getAppMockStore } from '../../../../../../library/src/store/mock'
import { mockAppState } from '../../../../../../library/src/state/mock'

export const dogSelectOptions = [
  { value: 'affenpinscher', text: 'affenpinscher' },
  { value: 'african', text: 'african' },
  { value: 'airedale', text: 'airedale' },
  { value: 'akita', text: 'akita' },
  { value: 'appenzeller', text: 'appenzeller' },
  { value: 'australian-shepherd', text: 'shepherd australian' },
  { value: 'basenji', text: 'basenji' },
  { value: 'beagle', text: 'beagle' },
  { value: 'bluetick', text: 'bluetick' },
  { value: 'borzoi', text: 'borzoi' },
  { value: 'bouvier', text: 'bouvier' },
  { value: 'boxer', text: 'boxer' },
  { value: 'brabancon', text: 'brabancon' },
  { value: 'briard', text: 'briard' },
  { value: 'buhund-norwegian', text: 'norwegian buhund' },
  { value: 'bulldog-boston', text: 'boston bulldog' },
  { value: 'bulldog-english', text: 'english bulldog' },
  { value: 'bulldog-french', text: 'french bulldog' },
  { value: 'bullterrier-staffordshire', text: 'staffordshire bullterrier' },
  { value: 'cairn', text: 'cairn' },
  { value: 'cattledog-australian', text: 'australian cattledog' },
  { value: 'chihuahua', text: 'chihuahua' },
  { value: 'chow', text: 'chow' },
  { value: 'clumber', text: 'clumber' },
  { value: 'cockapoo', text: 'cockapoo' },
  { value: 'collie-border', text: 'border collie' },
  { value: 'coonhound', text: 'coonhound' },
  { value: 'corgi-cardigan', text: 'cardigan corgi' },
  { value: 'cotondetulear', text: 'cotondetulear' },
  { value: 'dachshund', text: 'dachshund' },
  { value: 'dalmatian', text: 'dalmatian' },
  { value: 'dane-great', text: 'great dane' },
  { value: 'deerhound-scottish', text: 'scottish deerhound' },
  { value: 'dhole', text: 'dhole' },
  { value: 'dingo', text: 'dingo' },
  { value: 'doberman', text: 'doberman' },
  { value: 'elkhound-norwegian', text: 'norwegian elkhound' },
  { value: 'entlebucher', text: 'entlebucher' },
  { value: 'eskimo', text: 'eskimo' },
  { value: 'frise-bichon', text: 'bichon frise' },
  { value: 'germanshepherd', text: 'germanshepherd' },
  { value: 'greyhound-italian', text: 'italian greyhound' },
  { value: 'groenendael', text: 'groenendael' },
  { value: 'havanese', text: 'havanese' },
  { value: 'hound-afghan', text: 'afghan hound' },
  { value: 'hound-basset', text: 'basset hound' },
  { value: 'hound-blood', text: 'blood hound' },
  { value: 'hound-english', text: 'english hound' },
  { value: 'hound-ibizan', text: 'ibizan hound' },
  { value: 'hound-plott', text: 'plott hound' },
  { value: 'hound-walker', text: 'walker hound' },
  { value: 'husky', text: 'husky' },
  { value: 'keeshond', text: 'keeshond' },
  { value: 'kelpie', text: 'kelpie' },
  { value: 'komondor', text: 'komondor' },
  { value: 'kuvasz', text: 'kuvasz' },
  { value: 'labrador', text: 'labrador' },
  { value: 'leonberg', text: 'leonberg' },
  { value: 'lhasa', text: 'lhasa' },
  { value: 'malamute', text: 'malamute' },
  { value: 'malinois', text: 'malinois' },
  { value: 'maltese', text: 'maltese' },
  { value: 'mastiff-bull', text: 'bull mastiff' },
  { value: 'mastiff-english', text: 'english mastiff' },
  { value: 'mastiff-tibetan', text: 'tibetan mastiff' },
  { value: 'mexicanhairless', text: 'mexicanhairless' },
  { value: 'mix', text: 'mix' },
  { value: 'mountain-bernese', text: 'bernese mountain' },
  { value: 'mountain-swiss', text: 'swiss mountain' },
  { value: 'newfoundland', text: 'newfoundland' },
  { value: 'otterhound', text: 'otterhound' },
  { value: 'papillon', text: 'papillon' },
  { value: 'pekinese', text: 'pekinese' },
  { value: 'pembroke', text: 'pembroke' },
  { value: 'pinscher-miniature', text: 'miniature pinscher' },
  { value: 'pitbull', text: 'pitbull' },
  { value: 'pointer-german', text: 'german pointer' },
  { value: 'pointer-germanlonghair', text: 'germanlonghair pointer' },
  { value: 'pomeranian', text: 'pomeranian' },
  { value: 'poodle-miniature', text: 'miniature poodle' },
  { value: 'poodle-standard', text: 'standard poodle' },
  { value: 'poodle-toy', text: 'toy poodle' },
  { value: 'pug', text: 'pug' },
  { value: 'puggle', text: 'puggle' },
  { value: 'pyrenees', text: 'pyrenees' },
  { value: 'redbone', text: 'redbone' },
  { value: 'retriever-chesapeake', text: 'chesapeake retriever' },
  { value: 'retriever-curly', text: 'curly retriever' },
  { value: 'retriever-flatcoated', text: 'flatcoated retriever' },
  { value: 'retriever-golden', text: 'golden retriever' },
  { value: 'ridgeback-rhodesian', text: 'rhodesian ridgeback' },
  { value: 'rottweiler', text: 'rottweiler' },
  { value: 'saluki', text: 'saluki' },
  { value: 'samoyed', text: 'samoyed' },
  { value: 'schipperke', text: 'schipperke' },
  { value: 'schnauzer-giant', text: 'giant schnauzer' },
  { value: 'schnauzer-miniature', text: 'miniature schnauzer' },
  { value: 'setter-english', text: 'english setter' },
  { value: 'setter-gordon', text: 'gordon setter' },
  { value: 'setter-irish', text: 'irish setter' },
  { value: 'sheepdog-english', text: 'english sheepdog' },
  { value: 'sheepdog-shetland', text: 'shetland sheepdog' },
  { value: 'shiba', text: 'shiba' },
  { value: 'shihtzu', text: 'shihtzu' },
  { value: 'spaniel-blenheim', text: 'blenheim spaniel' },
  { value: 'spaniel-brittany', text: 'brittany spaniel' },
  { value: 'spaniel-cocker', text: 'cocker spaniel' },
  { value: 'spaniel-irish', text: 'irish spaniel' },
  { value: 'spaniel-japanese', text: 'japanese spaniel' },
  { value: 'spaniel-sussex', text: 'sussex spaniel' },
  { value: 'spaniel-welsh', text: 'welsh spaniel' },
  { value: 'springer-english', text: 'english springer' },
  { value: 'stbernard', text: 'stbernard' },
  { value: 'terrier-american', text: 'american terrier' },
  { value: 'terrier-australian', text: 'australian terrier' },
  { value: 'terrier-bedlington', text: 'bedlington terrier' },
  { value: 'terrier-border', text: 'border terrier' },
  { value: 'terrier-dandie', text: 'dandie terrier' },
  { value: 'terrier-fox', text: 'fox terrier' },
  { value: 'terrier-irish', text: 'irish terrier' },
  { value: 'terrier-kerryblue', text: 'kerryblue terrier' },
  { value: 'terrier-lakeland', text: 'lakeland terrier' },
  { value: 'terrier-norfolk', text: 'norfolk terrier' },
  { value: 'terrier-norwich', text: 'norwich terrier' },
  { value: 'terrier-patterdale', text: 'patterdale terrier' },
  { value: 'terrier-russell', text: 'russell terrier' },
  { value: 'terrier-scottish', text: 'scottish terrier' },
  { value: 'terrier-sealyham', text: 'sealyham terrier' },
  { value: 'terrier-silky', text: 'silky terrier' },
  { value: 'terrier-tibetan', text: 'tibetan terrier' },
  { value: 'terrier-toy', text: 'toy terrier' },
  { value: 'terrier-westhighland', text: 'westhighland terrier' },
  { value: 'terrier-wheaten', text: 'wheaten terrier' },
  { value: 'terrier-yorkshire', text: 'yorkshire terrier' },
  { value: 'vizsla', text: 'vizsla' },
  { value: 'waterdog-spanish', text: 'spanish waterdog' },
  { value: 'weimaraner', text: 'weimaraner' },
  { value: 'whippet', text: 'whippet' },
  { value: 'wolfhound-irish', text: 'irish wolfhound' },
]

export const catSelectOptions = [
  { value: 'Abyssinian', text: 'Abyssinian' },
  { value: 'Aegean', text: 'Aegean' },
  { value: 'American-Bobtail', text: 'American Bobtail' },
  { value: 'American-Curl', text: 'American Curl' },
  { value: 'American-Shorthair', text: 'American Shorthair' },
  { value: 'American-Wirehair', text: 'American Wirehair' },
  { value: 'Arabian-Mau', text: 'Arabian Mau' },
  { value: 'Australian-Mist', text: 'Australian Mist' },
  { value: 'Balinese', text: 'Balinese' },
  { value: 'Bambino', text: 'Bambino' },
  { value: 'Bengal', text: 'Bengal' },
  { value: 'Birman', text: 'Birman' },
  { value: 'Bombay', text: 'Bombay' },
  { value: 'British-Longhair', text: 'British Longhair' },
  { value: 'British-Shorthair', text: 'British Shorthair' },
  { value: 'Burmese', text: 'Burmese' },
  { value: 'Burmilla', text: 'Burmilla' },
  { value: 'California-Spangled', text: 'California Spangled' },
  { value: 'Chantilly-Tiffany', text: 'Chantilly-Tiffany' },
  { value: 'Chartreux', text: 'Chartreux' },
  { value: 'Chausie', text: 'Chausie' },
  { value: 'Cheetoh', text: 'Cheetoh' },
  { value: 'Colorpoint-Shorthair', text: 'Colorpoint Shorthair' },
  { value: 'Cornish-Rex', text: 'Cornish Rex' },
  { value: 'Cymric', text: 'Cymric' },
  { value: 'Cyprus', text: 'Cyprus' },
  { value: 'Devon-Rex', text: 'Devon Rex' },
  { value: 'Donskoy', text: 'Donskoy' },
  { value: 'Dragon-Li', text: 'Dragon Li' },
  { value: 'Egyptian-Mau', text: 'Egyptian Mau' },
  { value: 'European-Burmese', text: 'European Burmese' },
  { value: 'Exotic-Shorthair', text: 'Exotic Shorthair' },
  { value: 'Havana-Brown', text: 'Havana Brown' },
  { value: 'Himalayan', text: 'Himalayan' },
  { value: 'Japanese-Bobtail', text: 'Japanese Bobtail' },
  { value: 'Javanese', text: 'Javanese' },
  { value: 'Khao-Manee', text: 'Khao Manee' },
  { value: 'Korat', text: 'Korat' },
  { value: 'Kurilian', text: 'Kurilian' },
  { value: 'LaPerm', text: 'LaPerm' },
  { value: 'Maine-Coon', text: 'Maine Coon' },
  { value: 'Malayan', text: 'Malayan' },
  { value: 'Manx', text: 'Manx' },
  { value: 'Munchkin', text: 'Munchkin' },
  { value: 'Nebelung', text: 'Nebelung' },
  { value: 'Norwegian-Forest Cat', text: 'Norwegian Forest Cat' },
  { value: 'Ocicat', text: 'Ocicat' },
  { value: 'Oriental', text: 'Oriental' },
  { value: 'Persian', text: 'Persian' },
  { value: 'Pixie-bob', text: 'Pixie-bob' },
  { value: 'Ragamuffin', text: 'Ragamuffin' },
  { value: 'Ragdoll', text: 'Ragdoll' },
  { value: 'Russian-Blue', text: 'Russian Blue' },
  { value: 'Savannah', text: 'Savannah' },
  { value: 'Scottish-Fold', text: 'Scottish Fold' },
  { value: 'Selkirk-Rex', text: 'Selkirk Rex' },
  { value: 'Siamese', text: 'Siamese' },
  { value: 'Siberian', text: 'Siberian' },
  { value: 'Singapura', text: 'Singapura' },
  { value: 'Snowshoe', text: 'Snowshoe' },
]

export const dogSelectRender = (
  <Provider store={getAppMockStore(mockAppState)}>
    <Select options={dogSelectOptions} />
  </Provider>
)

export const catSelectRender = (
  <Provider store={getAppMockStore(mockAppState)}>
    <Select options={catSelectOptions} />
  </Provider>
)
